name: Generate Pacman Contribution SVG

permissions:
  contents: write  # REQUIRED so the workflow can push to the repo

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Pacman graph
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?color_snake=orange&color_dots=#161B22

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist"
          message: "Update Pacman animation"
